// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm50cavmiIhnrsPhS3YsvvgI-T-B6WEIU',
    appId: '1:774965574022:web:1a467e6ea92359399bd407',
    messagingSenderId: '774965574022',
    projectId: 'fruits-hub-e-commerce',
    authDomain: 'fruits-hub-e-commerce.firebaseapp.com',
    storageBucket: 'fruits-hub-e-commerce.firebasestorage.app',
    measurementId: 'G-YHM8Y7J0WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXmmrOuwCfZR1UMMgQUXCah8dAoFpGO84',
    appId: '1:774965574022:android:0c949d29611ed7479bd407',
    messagingSenderId: '774965574022',
    projectId: 'fruits-hub-e-commerce',
    storageBucket: 'fruits-hub-e-commerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Xtbn3VrYf1NWFbrJKwua2z6WW5D7Fho',
    appId: '1:774965574022:ios:f23f3b547ce616949bd407',
    messagingSenderId: '774965574022',
    projectId: 'fruits-hub-e-commerce',
    storageBucket: 'fruits-hub-e-commerce.firebasestorage.app',
    iosClientId: '774965574022-s5uav2totgiocnkr91dashgp04hfo449.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Xtbn3VrYf1NWFbrJKwua2z6WW5D7Fho',
    appId: '1:774965574022:ios:f23f3b547ce616949bd407',
    messagingSenderId: '774965574022',
    projectId: 'fruits-hub-e-commerce',
    storageBucket: 'fruits-hub-e-commerce.firebasestorage.app',
    iosClientId: '774965574022-s5uav2totgiocnkr91dashgp04hfo449.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm50cavmiIhnrsPhS3YsvvgI-T-B6WEIU',
    appId: '1:774965574022:web:e5bab65e7dc72b0d9bd407',
    messagingSenderId: '774965574022',
    projectId: 'fruits-hub-e-commerce',
    authDomain: 'fruits-hub-e-commerce.firebaseapp.com',
    storageBucket: 'fruits-hub-e-commerce.firebasestorage.app',
    measurementId: 'G-1R7ZZCD567',
  );
}
